# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171024_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Create_date',
            new_name='created_date',
        ),
    ]
